export const GET_ALL_TOONS_PENDING = 'GET_ALL_TOONS_PENDING';
export const GET_ALL_TOONS_FULFILLED = 'GET_ALL_TOONS_FULFILLED';
export const GET_ALL_TOONS_REJECTED = 'GET_ALL_TOONS_REJECTED';

export const GET_FAVS_PENDING = 'GET_FAVS_PENDING';
export const GET_FAVS_FULFILLED = 'GET_FAVS_FULFILLED';
export const GET_FAVS_REJECTED = 'GET_FAVS_REJECTED';
